/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gkovalechyn_testpluginloader_PluginLoader */

#ifndef _Included_net_gkovalechyn_testpluginloader_PluginLoader
#define _Included_net_gkovalechyn_testpluginloader_PluginLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_gkovalechyn_testpluginloader_PluginLoader
 * Method:    translateClass
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_gkovalechyn_testpluginloader_PluginLoader_translateClass
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_gkovalechyn_testpluginloader_PluginLoader
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_gkovalechyn_testpluginloader_PluginLoader_initialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
